CREATE TABLE ibb_members (
  mid int(11) NOT NULL auto_increment,
  name varchar(100) default NULL,
  password varchar(40) default NULL,
  birthday varchar(14) default '1 / 01 / 2002',
  email varchar(40) default NULL,
  posts blob,
  status varchar(40) default NULL,
  title varchar(50) default NULL,
  time varchar(50) default NULL,
  aviator varchar(100) default NULL,
  adminhide char(3) default NULL,
  timepref varchar(10) default '0',
  location varchar(100) default NULL,
  signature blob,
  options char(3) NOT NULL default 'on',
  aim varchar(50) NOT NULL default '',
  msn varchar(50) NOT NULL default '',
  icq varchar(50) NOT NULL default '',
  yahoo varchar(50) NOT NULL default '',
  occupation varchar(50) NOT NULL default '',
  website varchar(100) NOT NULL default '',
  avheight char(3) NOT NULL default '',
  avwidth char(3) NOT NULL default '',
  groupname varchar(50) NOT NULL default '',
  interests varchar(200) NOT NULL default '',
  PRIMARY KEY  (mid)
) TYPE=MyISAM